### ISSUE TITLE
"double set minus" into latex?

### ISSUE THREAD

**Issue by CoghettoR** [mimosa-project/emwiki#284]
## 目的

How to translate the "double set minus" into latex?

I found this solution (for the symbol "DIFFERENCE"), but is there an easier way? 
`\setminus\mspace{-10mu}\setminus`
https://em1.cs.shinshu-u.ac.jp/emwiki/release/article/setfam_1.html#K3

Is it possible to associate a latex macro to each symbol (here DIFFERENCE set_fam1) which would be used systematically in the wiki and referenced here in the symbols?
![image](https://user-images.githubusercontent.com/37469245/193250379-26a26654-b547-47f3-8267-519e60381a74.png)

## TaskList
+ [ ] 

## 留意事項
+ 

## 検討事項
+

**Comment by aabaa** [comment]
I have confirmed that the LaTeX definition syntax works locally as follows:

> $\newcommand{\dblsetminus}{\mathbin{{\setminus}\mspace{-5mu}{\setminus}}}$
> $\dblsetminus$

However, there is currently no function in this App to set this globally.
We would like to consider this feature as a future enhancement.
